text_color = "dark-gray"
author = "KQ4AFY"
favicon = ""
# site_logo = "/images/4556517.png"
description = ""
background_color_class = "bg-dark-blue"
body_classes = "avenir bg-near-white"
recent_posts_number = 3

[[ananke_socials]]
  name = "github"
  url = "https://github.com/jbouse"

[[ananke_socials]]
  name = "tiktok"
  url = "https://tiktok.com/@butonlyone.life"