hb:
  header:
    socials:
      email: station@kq4afy.xyz
  footer:
    socials:
      email: station@kq4afy.xyz
  blog:
    paginate: 9 # paginate.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      featured_posts: 6 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - blog
      #   - docs
    social_share_buttons:
      alignment: center
      media: 
      - facebook
      - twitter
      - linkedin
  gallery:
    paginate: 12
    # thumbnail_size: "x120"
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: ugns/kq4afy-hugo-site
      branch: main
