hb:
  blog:
    sidebar:
      profile:
        description: Amateur radio station operator
        company: KQ4AFY
        location: St. Cloud, FL
        hotline: 610-000-1659
        socials: &my_socials
          github: jbouse
          paypal: KQ4AFY
          telegram: KQ4AFY
          discord: rfT2kzvjfq
          tiktok: butonlyone.life
          email: operator@kq4afy.xyz    #       github: hbstack
    #       mastodon: https://techhub.social/@hbstack
    #       rss: true
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    # post_thumbnail: false # whether to show the thumbnails.
    post_date_format: ":date_full" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - blog
      #   - docs
      # taxonomies: false
    social_share_buttons:
      alignment: center
      media: 
      - facebook
      - twitter
      - linkedin
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: ugns/kq4afy-hugo-site
      branch: main
  footer:
    socials:
      <<: *my_socials
  gallery:
    date_sort_order: asc
    highlight_images_count: 10
    highlight_images_recursive: false
    paginate: 12
    thumbnail_size: x120
  google_fonts:
    families:
      - name: Roboto
  styles:
    hb_gallery_album_item_border_radius: 15px
    hb_gallery_album_item_gap: 10px
  header:
    socials:
      <<: *my_socials
  revision:
    date_format: :date_medium
