hb:
  full_width: false
  blog:
    sidebar:
      profile:
        description: Amateur radio station operator
        company: KQ4AFY
        location: St. Cloud, FL
        hotline: 6101659
        socials: &my_socials
          paypal: KQ4AFY
          telegram: KQ4AFY
          bluesky: kq4afy.radio
          rss: true
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    # post_thumbnail: false # whether to show the thumbnails.
    post_date_format: ":date_full" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - blog
      #   - docs
      # taxonomies: false
    social_share_buttons:
      alignment: center
      media: 
      - bluesky
      - facebook
      - twitter
      - linkedin
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: ugns/kq4afy-hugo-site
      branch: main
  footer:
    socials:
      <<: *my_socials
      _color: false
  gallery:
    date_sort_order: asc
    highlight_images_count: 10
    highlight_images_recursive: false
    paginate: 12
    thumbnail_size: x120
  google_fonts:
    families:
      - name: Roboto
  styles:
    hb_gallery_album_item_border_radius: 15px
    hb_gallery_album_item_gap: 10px
  header:
    socials:
      <<: *my_socials
  revision:
    date_format: :date_medium

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.
    sizes:
    - size: 16x16
    - size: 32x32
    - size: 150x150
    - rel: apple-touch-icon
      size: 180x180
    - size: 192x192

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'HB Theme'

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  shortcut_search: ["/"]

gravatar:
  default: wavatar
  rating: pg

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2