title = "Amateur Radio Station"
baseURL = "https://KQ4AFY.xyz/"
Copyright = "Jeremy KQ4AFY"
languageCode = "en-us"
theme = [ "github.com/theNewDynamic/gohugo-theme-ananke" ]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
enableGitInfo = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "dark-gray"
  author = "KQ4AFY"
  favicon = ""
  site_logo = "/images/4556517.png"
  description = ""
  date_format = ":date_long"
  background_color_class = "bg-dark-blue"
  body_classes = "avenir bg-near-white"
  recent_posts_number = 3
  disqusShortname = "kq4afy"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/jbouse"

[[params.ananke_socials]]
  name = "tiktok"
  url = "https://tiktok.com/@butonlyone.life"