order:
  - .jpg$
  - .png$
  - .gif$
targets:
  - name: AWS
    URL: 's3://kq4afy.xyz?region=us-east-1'
    cloudFrontDistributionID: E24XCU50JVWOD5
matchers:
  - pattern: ^.+\.(js|css|svg|ttf)$
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: true
  - pattern: ^.+\.(png|jpg|webp)$
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: false
  - pattern: ^sitemap\.xml$
    contentType: application/xml
    gzip: true
  - pattern: ^.+\.(html|xml|json)$
    gzip: true
