order = [".jpg$", ".png$", ".gif$"]

[[targets]]
name = "AWS"
URL = "s3://kq4afy.xyz?region=us-east-1"
cloudFrontDistributionID = "E24XCU50JVWOD5"

[[matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true